### ISSUE TITLE
Plugin not found on jazzy

### ISSUE THREAD

**Issue by StefanFabian** [ros-visualization/rqt_robot_steering#20]
I have installed the plugin using `ros-jazzy-rqt-robot-steering` but it does not show up in rqt and when starting manually, I get the following error message:

```
qt_gui_main() found no plugin matching "rqt_robot_steering.robot_steering.RobotSteering"
try passing the option "--force-discover"
Warning: class_loader.ClassLoader: SEVERE WARNING!!! Attempting to unload library while objects created by this loader exist in the heap! You should delete your objects before attempting to unload the library or destroying the ClassLoader. The library will NOT be unloaded.
         at line 127 in ./src/class_loader.cpp
```

**Comment by arne48** [comment]
Hello @StefanFabian,
I could reproduce your issue.
Can you try to start rqt like this? -> rqt --force-discover
Then under Plugins you also have "Robot Tools" and also the direct command "rqt_robot_steering" should work.

**Comment by StefanFabian** [comment]
Yes, that fixes the issue.
Leaving the issue open as this should probably not be necessary, though.
Feel free to close if this is intended (but then it should be documented).

**Comment by arne48** [comment]
It is indeed not very  intuitional that after the installation of a system package rqt has to be called with a switch to detect the newly installed plugin.

The cause is here: https://github.com/ros-visualization/qt_gui_core/blob/rolling/qt_gui/src/qt_gui/plugin_manager.py
Line 141 ff. 

After the first startup, rqt creates a rqt_gui.ini file in "~/.config/ros.org/" which also contains a timestamp.
Only the last discovery is older than one day, the plugin manager searches for all installed rqt plugins.
This feels quite arbitrary except being a round number.
Also the rqt_gui is not something that gets started in fast succession.
So I currently really don't see why the plugins shouldn't be detected on every startup.

I think it would be at least worth bringing up the issue in "ros-visualization/qt_gui_core"
and discuss, if in the name of user-friendliness such a change would make sense.
Also something in regard to your issue with the standalone option was brought up before (https://github.com/ros-visualization/qt_gui_core/issues/15).

**Comment by StefanFabian** [comment]
Okay, thank you for looking into it and the explanation!
I will close this as the issue is not related to the plugin.
